version: '2'

networks: 
  supplychain:

services: 

  ca_indonesianfarmorg1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.indonesianfarmorg1.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports: 
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/indonesianfarmorg1:/etc/hyperledger/fabric-ca-server
    container_name: ca.indonesianfarmorg1.supplychain.com
    hostname: ca.indonesianfarmorg1.supplychain.com
    networks: 
      - supplychain

  ca_usclientorg2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.usclientorg2.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports: 
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/usclientorg2:/etc/hyperledger/fabric-ca-server
    container_name: ca.usclientorg2.supplychain.com
    hostname: ca.usclientorg2.supplychain.com
    networks: 
      - supplychain

  ca_rubbershipperorg3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.rubbershipperorg3.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports: 
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/rubbershipperorg3:/etc/hyperledger/fabric-ca-server
    container_name: ca.rubbershipperorg3.supplychain.com
    hostname: ca.rubbershipperorg3.supplychain.com
    networks: 
      - supplychain

  ca_goodscustomorg4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.goodscustomorg4.supplychain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports: 
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/goodscustomorg4:/etc/hyperledger/fabric-ca-server
    container_name: ca.goodscustomorg4.supplychain.com
    hostname: ca.goodscustomorg4.supplychain.com
    networks: 
      - supplychain

  ca_orderer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports: 
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes: 
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks: 
      - supplychain