OrdererOrgs:
  - Name: Orderer
    Domain: supplychain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: IndonesianFarmOrg1
    Domain: indonesianfarmorg1.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: USClientOrg2
    Domain: usclientorg2.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - "localhost"
    Users:
      Count: 1
      
  - Name: RubberShipperOrg3
    Domain: rubbershipperorg3.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - "localhost"
    Users:
      Count: 1
      
  - Name: GoodsCustomOrg4
    Domain: goodscustomorg4.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - "localhost"
    Users:
      Count: 1